# Generated by Django 3.1.2 on 2021-04-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0002_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='ManualControl',
        ),
    ]
