# Generated by Django 3.1.2 on 2021-04-09 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0003_auto_20210409_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home_api.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('isBinary', models.BooleanField(default=True)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home_api.device')),
            ],
        ),
        migrations.DeleteModel(
            name='ManualControl',
        ),
    ]
