# Generated by Django 3.1.2 on 2021-04-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0004_auto_20210409_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinput',
            name='description',
            field=models.CharField(max_length=230, null=True),
        ),
        migrations.AddField(
            model_name='deviceoutput',
            name='description',
            field=models.CharField(max_length=230, null=True),
        ),
    ]
