# Generated by Django 3.1.2 on 2021-04-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0005_auto_20210409_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='url',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='deviceinput',
            unique_together={('device', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='deviceoutput',
            unique_together={('device', 'name')},
        ),
    ]
