# Generated by Django 3.1.2 on 2021-05-16 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0006_auto_20210409_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinput',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceinput', to='smart_home_api.device'),
        ),
        migrations.AlterField(
            model_name='deviceoutput',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceoutput', to='smart_home_api.device'),
        ),
        migrations.CreateModel(
            name='DeviceOutputAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=230, null=True)),
                ('url', models.BooleanField(default='/')),
                ('type', models.CharField(choices=[('POST', 'Post'), ('GET', 'Get')], default='GET', max_length=50)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('deviceOutput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputaction', to='smart_home_api.deviceoutput')),
            ],
            options={
                'unique_together': {('deviceOutput', 'name')},
            },
        ),
    ]
