# Generated by Django 3.1.2 on 2021-05-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0007_auto_20210516_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceoutputaction',
            name='url',
            field=models.TextField(default='/'),
        ),
    ]
