# Generated by Django 3.1.2 on 2021-08-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0008_auto_20210516_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinput',
            name='inputId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceoutput',
            name='outputId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
