# Generated by Django 3.1.2 on 2021-08-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0009_auto_20210815_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInputNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=230, null=True)),
                ('email', models.TextField(default='/')),
                ('condition', models.CharField(choices=[('EQUAL', 'Equal'), ('BIGGER_OR_EQUAL', 'Bigger Or Equal'), ('SMALLER_OR_EQUAL', 'Smaller Or Equal'), ('SMALLER', 'Smaller'), ('BIGGER', 'Bigger')], default='EQUAL', max_length=50)),
                ('threshold', models.IntegerField(default=1)),
                ('deviceIntput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputnotification', to='smart_home_api.deviceinput')),
            ],
            options={
                'unique_together': {('deviceIntput', 'name')},
            },
        ),
    ]
