# Generated by Django 3.1.2 on 2021-08-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0010_deviceinputnotification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deviceinputnotification',
            unique_together=set(),
        ),
    ]
