# Generated by Django 3.1.2 on 2021-08-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0013_auto_20210819_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceoutput',
            name='max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceoutput',
            name='min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
