# Generated by Django 3.1.2 on 2021-08-19 21:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0014_auto_20210819_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAdvanceAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=230, null=True)),
                ('isTurnOn', models.BooleanField(default=False)),
                ('inputs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('outputs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('content', models.CharField(max_length=230, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceaction', to='smart_home_api.device')),
            ],
            options={
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='deviceinputnotification',
            name='isTurnOn',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DeviceOutputAction',
        ),
    ]
