# Generated by Django 3.1.2 on 2021-08-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0017_auto_20210819_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='isAutoTurnOn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='isSmartLight',
            field=models.BooleanField(default=False),
        ),
    ]
