# Generated by Django 3.1.2 on 2021-08-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0018_auto_20210823_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='isAutoAirConditioner',
            field=models.BooleanField(default=False),
        ),
    ]
