# Generated by Django 3.1.2 on 2021-09-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0020_device_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='iconName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
