# Generated by Django 3.1.2 on 2021-09-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0021_device_iconname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOutputAutomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newValue', models.CharField(blank=True, max_length=230, null=True)),
                ('isTurnOn', models.BooleanField(default=False)),
                ('cron', models.CharField(max_length=230)),
                ('deviceOutput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputnotification', to='smart_home_api.deviceoutput')),
            ],
        ),
    ]
