# Generated by Django 3.1.2 on 2021-09-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0022_deviceoutputautomation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceoutputautomation',
            name='deviceOutput',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputautomation', to='smart_home_api.deviceoutput'),
        ),
    ]
