# Generated by Django 3.1.2 on 2021-09-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home_api', '0023_auto_20210911_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceoutput',
            name='isColorPicker',
            field=models.BooleanField(default=False),
        ),
    ]
